### ISSUE TITLE
about open source

### ISSUE THREAD

**Issue by HuitongJin** [a514514772/FedLAP-DP#1]
Hello Hui Bo, I am a beginner in federated learning differential privacy. I recently saw your work and it was very helpful to me. I would like to ask if you are interested in open source code?

**Comment by hui-po-wang** [comment]
Hi Huitong,

Thanks for your interest! We are preparing the code and hopefully will release it by the end of this month.

best,

**Comment by hui-po-wang** [comment]
Hi @HuitongJin ,

Thanks again for your interest. 

We just released the source with basic settings. If you have any questions, feel free to reach out.
